server:
  port: 8084
spring:
  rabbitmq:
    host: 192.168.25.128
    username: leyou
    password: leyou
    virtual-host: /leyou
  application:
    name: goods-web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      username: root
      password: root
      maximum-pool-size: 30
      minimum-idle: 10
    url: jdbc:mysql:///leyou?useUnicode=true&characterEncoding=utf-8
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5  # 每隔五秒发送一次心跳
    lease-expiration-duration-in-seconds: 10  #10秒不发送就过期
    instance-id: ${spring.application.name}:${server.port}