server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.25.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 15
leyou:
  jwt:
    pubKeyPath: C:\TEMP\rsa\rsa.pub
    cookieName: LY_TOKEN # cookie的名称